#exercícios 9.11 e 9.12
import classes_02b

usuario_01 = classes_02b.Admin('Cláudio', 'Almeida')
usuario_02 = classes_02b.Usuario('José', 'Almeida')
usuario_03 = classes_02b.Usuario('Antônio', 'Almeida')
print('*' * 60)
usuario_01.descricao_usuario()
usuario_02.descricao_usuario()
usuario_03.descricao_usuario()
print('*' * 60)
usuario_01.cumprimenta_usuario()
usuario_02.cumprimenta_usuario()
usuario_03.cumprimenta_usuario()
print('*' * 60)
print(f'O usuário {usuario_02.nome} tentou logar {usuario_02.get_tentativas_login()} vezes no sistema!')
usuario_02.incremeta_tentativas_login()
usuario_02.incremeta_tentativas_login()
usuario_02.incremeta_tentativas_login()
usuario_02.incremeta_tentativas_login()
print('*' * 60)
print(f'O usuário {usuario_01.nome} tem as seguintes permisssões de administrador: {usuario_01.permissoes.get_privilegios()}')
print('*' * 60)
print(f'O usuário {usuario_02.nome} tentou logar {usuario_02.get_tentativas_login()} vezes no sistema!')
usuario_02.reset_tentativas_login()
print('*' * 60)
print(f'O usuário {usuario_02.nome} tentou logar {usuario_02.get_tentativas_login()} vezes no sistema!')